import type { Metadata } from 'next'

import './globals.scss'
import { gilroy } from '@/fonts'
import Providers from './providers'
import PageLayout from '@/components/PageLayout'


export const metadata: Metadata = {
  title: 'Kleewish',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html>
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no" />
      </head>
      <body className={gilroy.className}>
        <Providers>
          <PageLayout>
            {children}
          </PageLayout>
        </Providers>
      </body>
    </html>
  )
}
